import * as fc from 'fast-check';
import {
  NotificationService,
  PushNotificationProvider,
  PushPayload,
  NotificationAction,
  NotificationRecord,
} from './notification.service';
import { AffectedUser } from './weather.service';

jest.mock('../config/database', () => ({
  query: jest.fn(),
}));

const { query: mockedQuery } = jest.requireMock('../config/database') as { query: jest.Mock };

/**
 * Property-Based Tests for Notification Service - Rain Notifications
 *
 * These tests verify universal properties that should hold across all valid inputs
 * using the fast-check framework with minimum 100 iterations per property.
 */

// ── Custom Generators ──────────────────────────────────────────────────────────

/** Generate a valid affected user */
const affectedUserGen = fc.record({
  id: fc.uuid(),
  phoneNumber: fc.tuple(
    fc.constantFrom('+91'),
    fc.integer({ min: 6000000000, max: 9999999999 }),
  ).map(([code, num]) => `${code}${num}`),
  language: fc.constantFrom('en', 'hi', 'gu'),
});

/** Generate a list of affected users (1-10 users) */
const affectedUsersGen = fc.array(affectedUserGen, { minLength: 1, maxLength: 10 });

// ── Tests ──────────────────────────────────────────────────────────────────────

describe('NotificationService - Property-Based Tests', () => {
  let service: NotificationService;
  let mockProvider: PushNotificationProvider;
  let sendSpy: jest.Mock;

  beforeEach(() => {
    sendSpy = jest.fn().mockResolvedValue(true);
    mockProvider = { send: sendSpy };
    service = new NotificationService(mockProvider);
    jest.clearAllMocks();
  });

  /**
   * Feature: waterlogging-alert-platform, Property 2: Rain Notification Structure
   *
   * **Validates: Requirements 1.2**
   *
   * Property: For any rain notification generated by the system, the notification
   * should contain the question "Is there rain in your area?" and provide Yes/No
   * response options.
   */
  describe('Property 2: Rain Notification Structure', () => {

    it('should include "Is there rain in your area?" in the notification body for any user', async () => {
      await fc.assert(
        fc.asyncProperty(
          affectedUserGen,
          async (user: AffectedUser) => {
            jest.clearAllMocks();

            // Mock DB insert returning a notification record
            mockedQuery.mockResolvedValueOnce({
              rows: [{
                id: `notif-${user.id}`,
                user_id: user.id,
                type: 'rain_detection',
                title: 'Rain Detected',
                body: 'Is there rain in your area?',
                sent_at: new Date(),
                responded_at: null,
                response: null,
              }],
            });

            const records = await service.sendRainNotification([user]);

            // The notification body must contain the required question
            expect(records.length).toBe(1);
            expect(records[0].body).toBe('Is there rain in your area?');
          },
        ),
        { numRuns: 100 },
      );
    });

    it('should include Yes/No action options in the push payload for any user', async () => {
      await fc.assert(
        fc.asyncProperty(
          affectedUserGen,
          async (user: AffectedUser) => {
            jest.clearAllMocks();
            sendSpy.mockResolvedValue(true);

            mockedQuery.mockResolvedValueOnce({
              rows: [{
                id: `notif-${user.id}`,
                user_id: user.id,
                type: 'rain_detection',
                title: 'Rain Detected',
                body: 'Is there rain in your area?',
                sent_at: new Date(),
                responded_at: null,
                response: null,
              }],
            });

            await service.sendRainNotification([user]);

            // Verify push was called and payload contains Yes/No actions
            expect(sendSpy).toHaveBeenCalledTimes(1);
            const [, payload]: [string, PushPayload] = sendSpy.mock.calls[0];

            expect(payload.notification.body).toBe('Is there rain in your area?');

            const actions: NotificationAction[] = JSON.parse(payload.data.actions);
            expect(actions).toHaveLength(2);

            const actionIds = actions.map((a) => a.id);
            const actionTitles = actions.map((a) => a.title);
            expect(actionIds).toContain('yes');
            expect(actionIds).toContain('no');
            expect(actionTitles).toContain('Yes');
            expect(actionTitles).toContain('No');
          },
        ),
        { numRuns: 100 },
      );
    });

    it('should produce consistent notification structure for any set of users', async () => {
      await fc.assert(
        fc.asyncProperty(
          affectedUsersGen,
          async (users: AffectedUser[]) => {
            jest.clearAllMocks();
            sendSpy.mockResolvedValue(true);

            // Mock DB insert for each user
            for (const user of users) {
              mockedQuery.mockResolvedValueOnce({
                rows: [{
                  id: `notif-${user.id}`,
                  user_id: user.id,
                  type: 'rain_detection',
                  title: 'Rain Detected',
                  body: 'Is there rain in your area?',
                  sent_at: new Date(),
                  responded_at: null,
                  response: null,
                }],
              });
            }

            const records = await service.sendRainNotification(users);

            // Every record must have the correct structure
            expect(records.length).toBe(users.length);
            for (const record of records) {
              expect(record.title).toBe('Rain Detected');
              expect(record.body).toBe('Is there rain in your area?');
              expect(record.type).toBe('rain_detection');
            }

            // Every push payload must have Yes/No actions
            expect(sendSpy).toHaveBeenCalledTimes(users.length);
            for (let i = 0; i < sendSpy.mock.calls.length; i++) {
              const [, payload]: [string, PushPayload] = sendSpy.mock.calls[i];
              const actions: NotificationAction[] = JSON.parse(payload.data.actions);
              expect(actions).toEqual([
                { id: 'yes', title: 'Yes' },
                { id: 'no', title: 'No' },
              ]);
            }
          },
        ),
        { numRuns: 100 },
      );
    });
  });
