import React, { createContext, useContext, useState } from 'react';

export type Lang = 'en' | 'hi' | 'gu';

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Navbar
    home: 'Home', liveMap: 'Live Map', about: 'About', howItWorks: 'How it Works', contact: 'Contact', getApp: 'Get the App',
    language: 'Language',

    // Landing — Hero
    heroBadge: 'Real-time flood intelligence for Indian cities',
    heroTitle1: "Don't get caught in the", heroTitle2: 'flood. Get ahead of it.',
    heroSub: 'CIVIX is a crowdsourced platform that delivers real-time waterlogging alerts, helping citizens and city authorities navigate monsoon season safely.',
    downloadAndroid: 'Download for Android', seeHow: 'See How it Works →',
    mapLoading: 'Live map — loading',
    legendSevere: 'Severe', legendModerate: 'Moderate', legendClear: 'Clear',
    liveFromCity: 'Live from your city',

    // Landing — Features
    featuresTitle: 'Features', feat1: 'Live Map', feat1d: 'Real-time waterlogging reports on an interactive map',
    feat2: 'Safe Navigation', feat2d: 'Avoid flooded roads with smart routing', feat3: 'Weather Alerts', feat3d: 'Get notified when rain starts in your area',
    feat4: 'Community Verified', feat4d: 'Upvote/downvote reports for accuracy', feat5: 'Multi-language', feat5d: 'Available in English, Hindi, and Gujarati',
    feat6: 'Partner API', feat6d: 'B2B API for delivery and logistics companies',
    whatCivixDoes: 'What CIVIX does',
    builtForChaos: 'Built for the chaos of',
    indianMonsoons: 'Indian monsoons',
    featSectionSub: 'Not another weather app. CIVIX is a ground-level intelligence network powered by the people who actually walk those streets.',
    alertsThatMatter: 'Alerts that matter',
    knowBeforeStepOut: 'Know before you step out',
    knowBeforeDesc: 'When someone reports waterlogging near you, you get a push notification within seconds. Not a forecast — an actual report from someone standing in the water right now.',
    avgReportToAlert: 'average time from report to alert',
    liveHeatmap: 'Live heatmap',
    seeCityLikeLocals: 'See the city like locals see it',
    seeCityDesc: 'Color-coded severity zones updated in real-time. Red means avoid, yellow means caution, green means clear. Plan your route before the auto driver refuses to go.',
    crowdsourced: 'Crowdsourced',
    crowdsourcedOneTap: 'Crowdsourced. One tap to report.',
    crowdsourcedDesc: 'No government sensor needed. Citizens report waterlogging with GPS-verified location and severity. The more people report, the smarter the system gets.',
    autoExpiryKeepsFresh: 'auto-expiry keeps data fresh',
    gpsLocationCaptured: 'GPS location captured',
    severityTagged: 'Severity tagged',
    highKneeDeep: 'High — knee-deep water',
    liveOnMap: 'Live on the map',
    nearbyUsersAlerted: 'Nearby users alerted instantly',
    offlineMode: 'Offline mode', offlineModeDesc: 'Reports sync when you\'re back online',
    gpsVerified: 'GPS verified', gpsVerifiedDesc: 'Location-accurate, tamper-proof reports',
    autoExpiry: 'Auto-expiry', autoExpiryDesc: 'Stale reports clear after 4 hours',
    worksAnywhere: 'Works anywhere', worksAnywhereDesc: 'GPS-based — no city restrictions',

    // Landing — How it Works
    howItWorksBadge: 'How it Works',
    threeStepsTo: 'Three steps to',
    saferCommutes: 'safer commutes',
    step1Title: 'Download & sign up',
    step1Desc: 'Get the CIVIX app. Verify with your email OTP — takes about 30 seconds. No phone number, no social login, no nonsense.',
    step2Title: 'Report what you see',
    step2Desc: 'Standing in water? One tap. Your GPS location and severity rating go live instantly. The community sees it in real-time.',
    step3Title: 'Stay ahead of the flood',
    step3Desc: 'Get alerts before you leave home. Check the live heatmap. Pick a dry route. Help your city respond faster.',

    // Landing — Contrast
    withoutCivix: 'Without CIVIX',
    withoutCivixDesc: 'You step out, it\'s flooded. No one warned you. You\'re stuck. The municipal corporation finds out three days later from a newspaper photo.',
    withCivix: 'With CIVIX',
    withCivixDesc: 'Someone two streets away reports waterlogging. You get an alert before you leave. You check the heatmap, take a different route, and reach on time. The city sees the data in real-time.',

    // Landing — CTA
    ctaTitle: "Monsoon season doesn't wait.", ctaSub: 'Neither should you.',

    // Landing — FAQ
    faqBadge: 'FAQ',
    faqTitle: 'Common',
    faqTitleGradient: 'questions',
    faq1q: 'Is CIVIX free?', faq1a: 'Yes. No ads, no premium tiers, no catch. It\'s a civic tech project built to help people.',
    faq2q: 'How accurate are the reports?', faq2a: 'Every report is GPS-verified. Stale data auto-expires after 4 hours so you only see what\'s happening right now.',
    faq3q: 'Does it work offline?', faq3a: 'Yes. Reports save locally and sync automatically when you\'re back online.',
    faq4q: 'Which cities does it cover?', faq4a: 'Anywhere with GPS. We started in Ahmedabad and have active users in 50+ Indian cities.',
    faq5q: 'Is my data private?', faq5a: 'We only collect location when you submit a report. No tracking, no data selling. Email is used only for login.',

    // Footer
    footerDesc: 'Community-driven waterlogging alert platform making Indian cities safer during monsoon season.',
    footerDownloadApp: 'Download App',
    footerPlatform: 'Platform',
    footerLiveMap: 'Live Map', footerAboutUs: 'About Us', footerContact: 'Contact', footerFeedback: 'Feedback', footerPrivacy: 'Privacy Policy',
    footerResources: 'Resources', footerFeatures: 'Features', footerHowItWorks: 'How it Works', footerFAQ: 'FAQ',
    footerGetInTouch: 'Get in Touch', footerEmailUs: 'Email Us', footerSendMessage: 'Send a Message',
    footerBuiltIn: '© 2026 CIVIX — Built in Ahmedabad, India',
    footerTagline: 'Crowdsourced flood intelligence for smarter cities',
    footerRights: 'All rights reserved.',

    // About Page
    aboutEyebrow: 'About CIVIX',
    aboutHeroTitle1: 'We got tired of drowning',
    aboutHeroTitle2: 'in',
    aboutHeroTitle3: 'preventable floods',
    aboutHeroLead: 'CIVIX started with a simple frustration: why does nobody know a road is flooded until they\'re standing in it? We built the tool we wished existed during every monsoon.',
    aboutStoryTitle: 'The reality of Indian monsoons',
    aboutStoryP1: 'Every year, the same cycle repeats. Heavy rain hits. Streets flood within minutes. Commuters wade through waist-deep water. Auto drivers refuse routes. Offices shut down. And the municipal corporation finds out from Twitter — hours later.',
    aboutStoryP2: 'The infrastructure gap is real, but the information gap is worse. There\'s no system that tells you "don\'t take MG Road right now, it\'s knee-deep." That\'s what we set out to fix.',
    aboutPullQuote: 'The problem isn\'t just flooding — it\'s that nobody knows about it until they\'re already stuck.',
    aboutWhatTitle: 'What we built',
    aboutWhatP1: 'CIVIX is a crowdsourced flood intelligence platform. Citizens report waterlogging from their phones with GPS-verified location and severity. Those reports go live instantly on a public heatmap. Nearby users get push alerts. City authorities get a real-time dashboard with analytics and hotspot data.',
    aboutWhatP2: 'No expensive IoT sensors. No government contracts. Just a mobile app, a map, and people who walk those streets every day.',
    aboutStat1Val: '~30s', aboutStat1Desc: 'from report to alert',
    aboutStat2Val: 'GPS', aboutStat2Desc: 'verified every report',
    aboutStat3Val: '4hr', aboutStat3Desc: 'auto-expiry keeps data fresh',
    aboutStat4Val: '24/7', aboutStat4Desc: 'always on, always free',
    aboutWhoTitle: 'Who it\'s for',
    aboutWhoCitizens: 'Citizens',
    aboutWhoCitizensDesc: 'Download the app, verify with email OTP, and you\'re in. Report waterlogging in one tap. Get alerts when flooding is reported near you. Check the live map before heading out — especially during heavy rain.',
    aboutWhoCityAuth: 'City authorities',
    aboutWhoCityAuthDesc: 'The admin dashboard gives you real-time severity data, historical trends, and geographic hotspots. Use crowdsourced intelligence to prioritize drainage work and deploy emergency response where it matters most.',
    aboutWhoResearchers: 'Researchers',
    aboutWhoResearchersDesc: 'Aggregated, anonymized flood data across Indian cities. Study urban drainage patterns, identify infrastructure failures, and build better predictive models for monsoon preparedness.',
    aboutTechTitle: 'Under the hood',
    aboutTechDesc: 'CIVIX runs on a modern, production-grade stack built for speed and reliability.',
    aboutCtaTitle1: 'Monsoon season doesn\'t wait.',
    aboutCtaTitle2: 'Neither should you.',
    aboutCtaDesc: 'Download CIVIX and help build real-time flood intelligence for your city.',
    viewLiveMap: 'View Live Map',

    // Contact Page
    contactEyebrow: 'Contact',
    contactHeroTitle1: 'Let\'s',
    contactHeroTitle2: 'talk',
    contactHeroLead: 'Have a question, feedback, or want to collaborate on making cities flood-smart? We\'re all ears.',
    contactEmailLabel: 'Email',
    contactEmailHint: 'We typically respond within 24 hours',
    contactLocationLabel: 'Location',
    contactLocationValue: 'Ahmedabad, Gujarat, India',
    contactSocialLabel: 'Social',
    contactSocialHint: 'Follow us for updates',
    contactFormTitle: 'Send us a message',
    contactFormDesc: 'Fill this out and we\'ll get back to you. Or just email us directly — whatever works.',
    contactNameLabel: 'Name', contactNamePlaceholder: 'Your name',
    contactEmailFieldLabel: 'Email', contactEmailPlaceholder: 'you@example.com',
    contactSubjectLabel: 'Subject', contactSubjectPlaceholder: 'What\'s this about?',
    contactMessageLabel: 'Message', contactMessagePlaceholder: 'Tell us what\'s on your mind...',
    contactSent: 'Sent — opening mail client...', contactSend: 'Send Message',
    contactCollabNote: 'Want to partner with us? We\'re always open to working with civic-minded teams, municipal bodies, and organizations building for urban resilience. Just drop us a line.',

    // How It Works Page
    hiwEyebrow: 'How CIVIX Works',
    hiwHeroTitle1: 'Real-time flood intelligence,',
    hiwHeroTitle2: 'powered by citizens',
    hiwHeroLead: 'CIVIX is a citizen-powered platform: a mobile app for reporting, a live public map for awareness, and smart alerts to keep you safe. Here\'s how it all fits together.',
    hiwScrollToExplore: 'Scroll to explore',
    hiwPlatformLabel: '01 — The Platform',
    hiwPlatformTitle: 'Three parts, one network',
    hiwPlatformDesc: 'CIVIX has three components that work together to create a real-time waterlogging intelligence network.',
    hiwMobileApp: 'Mobile App',
    hiwMobileAppDesc: 'Citizens report waterlogging with GPS-verified location and severity level. Reports sync instantly — or queue offline and sync when back online.',
    hiwLiveMap: 'Live Map',
    hiwLiveMapDesc: 'A public heatmap showing all active waterlogging reports. Color-coded by severity — red for high, orange for medium, green for low. No login required.',
    hiwPushAlerts: 'Push Alerts',
    hiwPushAlertsDesc: 'When someone reports waterlogging near you, you get notified instantly. The system also detects rainfall and proactively asks nearby users to report conditions.',
    hiwReportingLabel: '02 — Reporting Flow',
    hiwReportingTitle: 'From spotting to alerting in 30 seconds',
    hiwReportingDesc: 'The entire flow from seeing waterlogging to alerting nearby users is almost instant.',
    hiwStep1Title: 'Open the app',
    hiwStep1Desc: 'Standing in a waterlogged area? Open CIVIX and tap "Report". The app captures your GPS coordinates automatically.',
    hiwStep2Title: 'Tag the severity',
    hiwStep2Desc: 'Select Low, Medium, or High based on water depth. The report is tagged with your location, severity, and timestamp.',
    hiwStep3Title: 'Report goes live',
    hiwStep3Desc: 'The report appears on the public heatmap instantly. A 500m radius zone is drawn around the location. Nearby users get push notifications.',
    hiwStep4Title: 'Auto-expiry keeps it fresh',
    hiwStep4Desc: 'Reports expire after 4 hours. "Clear" reports cancel nearby waterlogged ones within 500m. The map always shows what\'s happening right now.',
    hiwAuthLabel: '03 — Getting Started',
    hiwAuthTitle: 'Simple, passwordless sign-up',
    hiwAuthDesc: 'No phone number, no social login, no passwords to remember.',
    hiwAuthEnterEmail: 'Enter email',
    hiwAuthVerifyOTP: 'Verify OTP',
    hiwAuthYoureIn: 'You\'re in',
    hiwPrivacyTitle: 'Privacy first',
    hiwPrivacyDesc: 'We only collect your email for authentication. No phone number, no social profiles, no tracking. Your reports appear anonymously on the map — your identity is never shown publicly.',
    hiwSmartLabel: '04 — Smart Features',
    hiwSmartTitle: 'Intelligence built in',
    hiwOfflineSupport: 'Offline support',
    hiwOfflineSupportDesc: 'Reports are saved on your phone and automatically synced when connectivity returns.',
    hiwLocationIntel: 'Location intelligence',
    hiwLocationIntelDesc: 'Reports are geographically indexed using real Earth geometry. You see what\'s relevant to your area.',
    hiwWeatherDetection: 'Weather detection',
    hiwWeatherDetectionDesc: 'CIVIX monitors real-time rainfall. When precipitation is detected, you get a notification to report conditions.',
    hiwSpamProtection: 'Spam protection',
    hiwSpamProtectionDesc: 'Daily limits on reports prevent abuse while still letting active citizens contribute.',
    hiwLiveAggregation: 'Live aggregation',
    hiwLiveAggregationDesc: 'The map aggregates reports by area, showing severity levels and density. Always fresh, always fast.',
    hiwCtaTitle: 'Ready to try it?',
    hiwCtaDesc: 'Download the app and start reporting. Or check the live map to see what\'s happening in your city right now.',

    // Feedback Page
    fbEyebrow: 'Feedback',
    fbHeroTitle1: 'Help us make CIVIX',
    fbHeroTitle2: 'better',
    fbHeroLead: 'We\'re building this for you. Tell us what\'s working, what\'s broken, or what you wish existed. Every suggestion is public — transparency builds trust.',
    fbFormTitle: 'Share your thoughts',
    fbSuccess: 'Thanks for your feedback — it\'s now visible below.',
    fbError: 'Failed to submit. Please try again.',
    fbNameLabel: 'Name', fbNamePlaceholder: 'Your name',
    fbEmailLabel: 'Email (optional)', fbEmailPlaceholder: 'you@example.com',
    fbTypeLabel: 'What kind of feedback?',
    fbTypeSuggestion: 'Suggestion', fbTypeBug: 'Bug', fbTypeFeature: 'Feature', fbTypeOther: 'Other',
    fbMessageLabel: 'Your feedback', fbMessagePlaceholder: 'Tell us what\'s on your mind...',
    fbSubmitting: 'Submitting...', fbPostFeedback: 'Post Feedback',
    fbCommunityTitle: 'Community feedback',
    fbPost: 'post', fbPosts: 'posts',
    fbFilterAll: 'All',
    fbEmpty: 'No feedback yet. Be the first to share your thoughts.',
    fbJustNow: 'just now',
  },
  hi: {
    // Navbar
    home: 'होम', liveMap: 'लाइव मैप', about: 'हमारे बारे में', howItWorks: 'कैसे काम करता है', contact: 'संपर्क', getApp: 'ऐप डाउनलोड करें',
    language: 'भाषा',

    // Landing — Hero
    heroBadge: 'भारतीय शहरों के लिए रीयल-टाइम बाढ़ इंटेलिजेंस',
    heroTitle1: 'बाढ़ में फंसें नहीं', heroTitle2: 'उससे आगे रहें।',
    heroSub: 'CIVIX एक क्राउडसोर्स्ड प्लेटफॉर्म है जो रीयल-टाइम जलभराव अलर्ट देता है, नागरिकों और शहर प्रशासन को मानसून में सुरक्षित नेविगेट करने में मदद करता है।',
    downloadAndroid: 'Android के लिए डाउनलोड करें', seeHow: 'देखें कैसे काम करता है →',
    mapLoading: 'लाइव मैप — लोड हो रहा है',
    legendSevere: 'गंभीर', legendModerate: 'मध्यम', legendClear: 'सामान्य',
    liveFromCity: 'आपके शहर से लाइव',

    // Landing — Features
    featuresTitle: 'विशेषताएं', feat1: 'लाइव मैप', feat1d: 'इंटरैक्टिव मैप पर रीयल-टाइम जलभराव रिपोर्ट',
    feat2: 'सुरक्षित नेविगेशन', feat2d: 'स्मार्ट रूटिंग से बाढ़ वाली सड़कों से बचें', feat3: 'मौसम अलर्ट', feat3d: 'जब आपके क्षेत्र में बारिश शुरू हो तो सूचना पाएं',
    feat4: 'समुदाय सत्यापित', feat4d: 'सटीकता के लिए रिपोर्ट को अपवोट/डाउनवोट करें', feat5: 'बहुभाषी', feat5d: 'अंग्रेजी, हिंदी और गुजराती में उपलब्ध',
    feat6: 'पार्टनर API', feat6d: 'डिलीवरी और लॉजिस्टिक्स कंपनियों के लिए B2B API',
    whatCivixDoes: 'CIVIX क्या करता है',
    builtForChaos: 'भारतीय मानसून की',
    indianMonsoons: 'अराजकता के लिए बनाया गया',
    featSectionSub: 'यह कोई और मौसम ऐप नहीं है। CIVIX एक जमीनी स्तर का इंटेलिजेंस नेटवर्क है जो उन लोगों द्वारा संचालित है जो वास्तव में उन सड़कों पर चलते हैं।',
    alertsThatMatter: 'महत्वपूर्ण अलर्ट',
    knowBeforeStepOut: 'बाहर निकलने से पहले जानें',
    knowBeforeDesc: 'जब कोई आपके पास जलभराव की रिपोर्ट करता है, तो आपको कुछ ही सेकंड में पुश नोटिफिकेशन मिलता है। यह पूर्वानुमान नहीं — पानी में खड़े किसी व्यक्ति की वास्तविक रिपोर्ट है।',
    avgReportToAlert: 'रिपोर्ट से अलर्ट तक औसत समय',
    liveHeatmap: 'लाइव हीटमैप',
    seeCityLikeLocals: 'शहर को स्थानीय लोगों की तरह देखें',
    seeCityDesc: 'रीयल-टाइम में अपडेट होने वाले रंग-कोडित गंभीरता क्षेत्र। लाल का मतलब बचें, पीला सावधानी, हरा सामान्य। ऑटो ड्राइवर के मना करने से पहले अपना रास्ता तय करें।',
    crowdsourced: 'क्राउडसोर्स्ड',
    crowdsourcedOneTap: 'क्राउडसोर्स्ड। एक टैप में रिपोर्ट करें।',
    crowdsourcedDesc: 'किसी सरकारी सेंसर की जरूरत नहीं। नागरिक GPS-सत्यापित स्थान और गंभीरता के साथ जलभराव की रिपोर्ट करते हैं। जितने ज्यादा लोग रिपोर्ट करें, सिस्टम उतना स्मार्ट बनता है।',
    autoExpiryKeepsFresh: 'ऑटो-एक्सपायरी डेटा को ताज़ा रखती है',
    gpsLocationCaptured: 'GPS स्थान कैप्चर किया गया',
    severityTagged: 'गंभीरता टैग की गई',
    highKneeDeep: 'उच्च — घुटने तक पानी',
    liveOnMap: 'मैप पर लाइव',
    nearbyUsersAlerted: 'आस-पास के उपयोगकर्ताओं को तुरंत सूचित किया गया',
    offlineMode: 'ऑफलाइन मोड', offlineModeDesc: 'ऑनलाइन होने पर रिपोर्ट सिंक होती हैं',
    gpsVerified: 'GPS सत्यापित', gpsVerifiedDesc: 'स्थान-सटीक, छेड़छाड़-रोधी रिपोर्ट',
    autoExpiry: 'ऑटो-एक्सपायरी', autoExpiryDesc: 'पुरानी रिपोर्ट 4 घंटे बाद हट जाती हैं',
    worksAnywhere: 'कहीं भी काम करे', worksAnywhereDesc: 'GPS-आधारित — कोई शहर प्रतिबंध नहीं',

    // Landing — How it Works
    howItWorksBadge: 'कैसे काम करता है',
    threeStepsTo: 'तीन कदम',
    saferCommutes: 'सुरक्षित यात्रा के लिए',
    step1Title: 'डाउनलोड करें और साइन अप करें',
    step1Desc: 'CIVIX ऐप डाउनलोड करें। ईमेल OTP से सत्यापित करें — लगभग 30 सेकंड लगते हैं। कोई फोन नंबर नहीं, कोई सोशल लॉगिन नहीं।',
    step2Title: 'जो दिखे वो रिपोर्ट करें',
    step2Desc: 'पानी में खड़े हैं? एक टैप। आपका GPS स्थान और गंभीरता रेटिंग तुरंत लाइव हो जाती है। समुदाय इसे रीयल-टाइम में देखता है।',
    step3Title: 'बाढ़ से आगे रहें',
    step3Desc: 'घर से निकलने से पहले अलर्ट पाएं। लाइव हीटमैप देखें। सूखा रास्ता चुनें। अपने शहर को तेज़ी से प्रतिक्रिया करने में मदद करें।',

    // Landing — Contrast
    withoutCivix: 'CIVIX के बिना',
    withoutCivixDesc: 'आप बाहर निकलते हैं, बाढ़ आई है। किसी ने चेतावनी नहीं दी। आप फंस गए। नगर निगम को तीन दिन बाद अखबार की फोटो से पता चलता है।',
    withCivix: 'CIVIX के साथ',
    withCivixDesc: 'दो गलियां दूर कोई जलभराव की रिपोर्ट करता है। आपको निकलने से पहले अलर्ट मिलता है। आप हीटमैप देखते हैं, दूसरा रास्ता लेते हैं, और समय पर पहुंचते हैं। शहर को रीयल-टाइम में डेटा दिखता है।',

    // Landing — CTA
    ctaTitle: 'मानसून का मौसम इंतज़ार नहीं करता।', ctaSub: 'आपको भी नहीं करना चाहिए।',

    // Landing — FAQ
    faqBadge: 'अक्सर पूछे जाने वाले प्रश्न',
    faqTitle: 'सामान्य',
    faqTitleGradient: 'प्रश्न',
    faq1q: 'क्या CIVIX मुफ्त है?', faq1a: 'हां। कोई विज्ञापन नहीं, कोई प्रीमियम टियर नहीं, कोई शर्त नहीं। यह लोगों की मदद के लिए बनाई गई एक नागरिक तकनीक परियोजना है।',
    faq2q: 'रिपोर्ट कितनी सटीक हैं?', faq2a: 'हर रिपोर्ट GPS-सत्यापित है। पुराना डेटा 4 घंटे बाद स्वतः समाप्त हो जाता है ताकि आप केवल वही देखें जो अभी हो रहा है।',
    faq3q: 'क्या यह ऑफलाइन काम करता है?', faq3a: 'हां। रिपोर्ट स्थानीय रूप से सहेजी जाती हैं और ऑनलाइन होने पर स्वचालित रूप से सिंक होती हैं।',
    faq4q: 'यह किन शहरों में उपलब्ध है?', faq4a: 'GPS वाली कहीं भी। हमने अहमदाबाद से शुरू किया और 50+ भारतीय शहरों में सक्रिय उपयोगकर्ता हैं।',
    faq5q: 'क्या मेरा डेटा निजी है?', faq5a: 'हम केवल रिपोर्ट सबमिट करते समय स्थान एकत्र करते हैं। कोई ट्रैकिंग नहीं, कोई डेटा बिक्री नहीं। ईमेल केवल लॉगिन के लिए उपयोग होता है।',

    // Footer
    footerDesc: 'समुदाय-संचालित जलभराव चेतावनी प्लेटफॉर्म जो मानसून के मौसम में भारतीय शहरों को सुरक्षित बनाता है।',
    footerDownloadApp: 'ऐप डाउनलोड करें',
    footerPlatform: 'प्लेटफॉर्म',
    footerLiveMap: 'लाइव मैप', footerAboutUs: 'हमारे बारे में', footerContact: 'संपर्क', footerFeedback: 'प्रतिक्रिया', footerPrivacy: 'गोपनीयता नीति',
    footerResources: 'संसाधन', footerFeatures: 'विशेषताएं', footerHowItWorks: 'कैसे काम करता है', footerFAQ: 'अक्सर पूछे जाने वाले प्रश्न',
    footerGetInTouch: 'संपर्क करें', footerEmailUs: 'ईमेल करें', footerSendMessage: 'संदेश भेजें',
    footerBuiltIn: '© 2026 CIVIX — अहमदाबाद, भारत में निर्मित',
    footerTagline: 'स्मार्ट शहरों के लिए क्राउडसोर्स्ड बाढ़ इंटेलिजेंस',
    footerRights: 'सर्वाधिकार सुरक्षित।',

    // About Page
    aboutEyebrow: 'CIVIX के बारे में',
    aboutHeroTitle1: 'हम थक गए थे डूबते-डूबते',
    aboutHeroTitle2: '',
    aboutHeroTitle3: 'रोकी जा सकने वाली बाढ़ में',
    aboutHeroLead: 'CIVIX एक साधारण निराशा से शुरू हुआ: किसी को क्यों नहीं पता कि सड़क पर बाढ़ आई है जब तक वे उसमें खड़े न हों? हमने वह उपकरण बनाया जो हम हर मानसून में चाहते थे।',
    aboutStoryTitle: 'भारतीय मानसून की वास्तविकता',
    aboutStoryP1: 'हर साल वही चक्र दोहराता है। भारी बारिश होती है। सड़कें मिनटों में डूब जाती हैं। यात्री कमर तक पानी में चलते हैं। ऑटो ड्राइवर रास्ते से मना कर देते हैं। दफ्तर बंद हो जाते हैं। और नगर निगम को ट्विटर से पता चलता है — घंटों बाद।',
    aboutStoryP2: 'बुनियादी ढांचे की कमी वास्तविक है, लेकिन सूचना की कमी और भी बदतर है। कोई ऐसी प्रणाली नहीं है जो आपको बताए "अभी MG रोड मत लो, घुटने तक पानी है।" यही हमने ठीक करने की ठानी।',
    aboutPullQuote: 'समस्या सिर्फ बाढ़ नहीं है — यह है कि किसी को इसके बारे में तब तक पता नहीं चलता जब तक वे पहले से फंस नहीं जाते।',
    aboutWhatTitle: 'हमने क्या बनाया',
    aboutWhatP1: 'CIVIX एक क्राउडसोर्स्ड बाढ़ इंटेलिजेंस प्लेटफॉर्म है। नागरिक अपने फोन से GPS-सत्यापित स्थान और गंभीरता के साथ जलभराव की रिपोर्ट करते हैं। वे रिपोर्ट तुरंत सार्वजनिक हीटमैप पर लाइव हो जाती हैं। आस-पास के उपयोगकर्ताओं को पुश अलर्ट मिलते हैं। शहर प्रशासन को एनालिटिक्स और हॉटस्पॉट डेटा के साथ रीयल-टाइम डैशबोर्ड मिलता है।',
    aboutWhatP2: 'कोई महंगे IoT सेंसर नहीं। कोई सरकारी अनुबंध नहीं। बस एक मोबाइल ऐप, एक मैप, और वे लोग जो हर दिन उन सड़कों पर चलते हैं।',
    aboutStat1Val: '~30s', aboutStat1Desc: 'रिपोर्ट से अलर्ट तक',
    aboutStat2Val: 'GPS', aboutStat2Desc: 'हर रिपोर्ट सत्यापित',
    aboutStat3Val: '4hr', aboutStat3Desc: 'ऑटो-एक्सपायरी डेटा ताज़ा रखती है',
    aboutStat4Val: '24/7', aboutStat4Desc: 'हमेशा चालू, हमेशा मुफ्त',
    aboutWhoTitle: 'यह किसके लिए है',
    aboutWhoCitizens: 'नागरिक',
    aboutWhoCitizensDesc: 'ऐप डाउनलोड करें, ईमेल OTP से सत्यापित करें, और आप अंदर हैं। एक टैप में जलभराव की रिपोर्ट करें। जब आपके पास बाढ़ की रिपोर्ट हो तो अलर्ट पाएं। बाहर निकलने से पहले लाइव मैप देखें — खासकर भारी बारिश में।',
    aboutWhoCityAuth: 'शहर प्रशासन',
    aboutWhoCityAuthDesc: 'एडमिन डैशबोर्ड आपको रीयल-टाइम गंभीरता डेटा, ऐतिहासिक रुझान और भौगोलिक हॉटस्पॉट देता है। ड्रेनेज कार्य को प्राथमिकता देने और आपातकालीन प्रतिक्रिया तैनात करने के लिए क्राउडसोर्स्ड इंटेलिजेंस का उपयोग करें।',
    aboutWhoResearchers: 'शोधकर्ता',
    aboutWhoResearchersDesc: 'भारतीय शहरों में एकत्रित, गुमनाम बाढ़ डेटा। शहरी जल निकासी पैटर्न का अध्ययन करें, बुनियादी ढांचे की विफलताओं की पहचान करें, और मानसून तैयारी के लिए बेहतर पूर्वानुमान मॉडल बनाएं।',
    aboutTechTitle: 'अंदर की तकनीक',
    aboutTechDesc: 'CIVIX गति और विश्वसनीयता के लिए बनाए गए आधुनिक, प्रोडक्शन-ग्रेड स्टैक पर चलता है।',
    aboutCtaTitle1: 'मानसून का मौसम इंतज़ार नहीं करता।',
    aboutCtaTitle2: 'आपको भी नहीं करना चाहिए।',
    aboutCtaDesc: 'CIVIX डाउनलोड करें और अपने शहर के लिए रीयल-टाइम बाढ़ इंटेलिजेंस बनाने में मदद करें।',
    viewLiveMap: 'लाइव मैप देखें',

    // Contact Page
    contactEyebrow: 'संपर्क',
    contactHeroTitle1: 'आइए',
    contactHeroTitle2: 'बात करें',
    contactHeroLead: 'कोई सवाल, प्रतिक्रिया, या शहरों को बाढ़-स्मार्ट बनाने में सहयोग करना चाहते हैं? हम सुन रहे हैं।',
    contactEmailLabel: 'ईमेल',
    contactEmailHint: 'हम आमतौर पर 24 घंटे के भीतर जवाब देते हैं',
    contactLocationLabel: 'स्थान',
    contactLocationValue: 'अहमदाबाद, गुजरात, भारत',
    contactSocialLabel: 'सोशल',
    contactSocialHint: 'अपडेट के लिए फॉलो करें',
    contactFormTitle: 'हमें संदेश भेजें',
    contactFormDesc: 'यह भरें और हम आपसे संपर्क करेंगे। या सीधे ईमेल करें — जो भी सुविधाजनक हो।',
    contactNameLabel: 'नाम', contactNamePlaceholder: 'आपका नाम',
    contactEmailFieldLabel: 'ईमेल', contactEmailPlaceholder: 'you@example.com',
    contactSubjectLabel: 'विषय', contactSubjectPlaceholder: 'यह किस बारे में है?',
    contactMessageLabel: 'संदेश', contactMessagePlaceholder: 'हमें बताएं आपके मन में क्या है...',
    contactSent: 'भेजा गया — मेल क्लाइंट खुल रहा है...', contactSend: 'संदेश भेजें',
    contactCollabNote: 'हमारे साथ साझेदारी करना चाहते हैं? हम हमेशा नागरिक-उन्मुख टीमों, नगर निकायों और शहरी लचीलापन के लिए काम करने वाले संगठनों के साथ काम करने के लिए तैयार हैं। बस हमें लिखें।',

    // How It Works Page
    hiwEyebrow: 'CIVIX कैसे काम करता है',
    hiwHeroTitle1: 'रीयल-टाइम बाढ़ इंटेलिजेंस,',
    hiwHeroTitle2: 'नागरिकों द्वारा संचालित',
    hiwHeroLead: 'CIVIX एक नागरिक-संचालित प्लेटफॉर्म है: रिपोर्टिंग के लिए मोबाइल ऐप, जागरूकता के लिए लाइव सार्वजनिक मैप, और आपको सुरक्षित रखने के लिए स्मार्ट अलर्ट। यहां बताया गया है कि यह सब कैसे जुड़ता है।',
    hiwScrollToExplore: 'एक्सप्लोर करने के लिए स्क्रॉल करें',
    hiwPlatformLabel: '01 — प्लेटफॉर्म',
    hiwPlatformTitle: 'तीन भाग, एक नेटवर्क',
    hiwPlatformDesc: 'CIVIX के तीन घटक हैं जो मिलकर रीयल-टाइम जलभराव इंटेलिजेंस नेटवर्क बनाते हैं।',
    hiwMobileApp: 'मोबाइल ऐप',
    hiwMobileAppDesc: 'नागरिक GPS-सत्यापित स्थान और गंभीरता स्तर के साथ जलभराव की रिपोर्ट करते हैं। रिपोर्ट तुरंत सिंक होती हैं — या ऑफलाइन कतार में लगती हैं और वापस ऑनलाइन होने पर सिंक होती हैं।',
    hiwLiveMap: 'लाइव मैप',
    hiwLiveMapDesc: 'सभी सक्रिय जलभराव रिपोर्ट दिखाने वाला सार्वजनिक हीटमैप। गंभीरता के अनुसार रंग-कोडित — उच्च के लिए लाल, मध्यम के लिए नारंगी, कम के लिए हरा। लॉगिन आवश्यक नहीं।',
    hiwPushAlerts: 'पुश अलर्ट',
    hiwPushAlertsDesc: 'जब कोई आपके पास जलभराव की रिपोर्ट करता है, तो आपको तुरंत सूचित किया जाता है। सिस्टम बारिश का भी पता लगाता है और सक्रिय रूप से आस-पास के उपयोगकर्ताओं से स्थिति रिपोर्ट करने के लिए कहता है।',
    hiwReportingLabel: '02 — रिपोर्टिंग प्रवाह',
    hiwReportingTitle: 'देखने से अलर्ट करने तक 30 सेकंड में',
    hiwReportingDesc: 'जलभराव देखने से लेकर आस-पास के उपयोगकर्ताओं को अलर्ट करने तक का पूरा प्रवाह लगभग तुरंत है।',
    hiwStep1Title: 'ऐप खोलें',
    hiwStep1Desc: 'जलभराव वाले क्षेत्र में खड़े हैं? CIVIX खोलें और "रिपोर्ट" पर टैप करें। ऐप स्वचालित रूप से आपके GPS निर्देशांक कैप्चर करता है।',
    hiwStep2Title: 'गंभीरता टैग करें',
    hiwStep2Desc: 'पानी की गहराई के आधार पर कम, मध्यम या उच्च चुनें। रिपोर्ट आपके स्थान, गंभीरता और समय के साथ टैग की जाती है।',
    hiwStep3Title: 'रिपोर्ट लाइव हो जाती है',
    hiwStep3Desc: 'रिपोर्ट तुरंत सार्वजनिक हीटमैप पर दिखाई देती है। स्थान के चारों ओर 500 मीटर का क्षेत्र बनाया जाता है। आस-पास के उपयोगकर्ताओं को पुश नोटिफिकेशन मिलते हैं।',
    hiwStep4Title: 'ऑटो-एक्सपायरी इसे ताज़ा रखती है',
    hiwStep4Desc: 'रिपोर्ट 4 घंटे बाद समाप्त हो जाती हैं। "सामान्य" रिपोर्ट 500 मीटर के भीतर आस-पास की जलभराव रिपोर्ट रद्द कर देती हैं। मैप हमेशा दिखाता है कि अभी क्या हो रहा है।',
    hiwAuthLabel: '03 — शुरू करना',
    hiwAuthTitle: 'सरल, पासवर्ड-रहित साइन-अप',
    hiwAuthDesc: 'कोई फोन नंबर नहीं, कोई सोशल लॉगिन नहीं, कोई पासवर्ड याद रखने की जरूरत नहीं।',
    hiwAuthEnterEmail: 'ईमेल दर्ज करें',
    hiwAuthVerifyOTP: 'OTP सत्यापित करें',
    hiwAuthYoureIn: 'आप अंदर हैं',
    hiwPrivacyTitle: 'गोपनीयता पहले',
    hiwPrivacyDesc: 'हम केवल प्रमाणीकरण के लिए आपका ईमेल एकत्र करते हैं। कोई फोन नंबर नहीं, कोई सोशल प्रोफाइल नहीं, कोई ट्रैकिंग नहीं। आपकी रिपोर्ट मैप पर गुमनाम रूप से दिखाई देती हैं — आपकी पहचान कभी सार्वजनिक रूप से नहीं दिखाई जाती।',
    hiwSmartLabel: '04 — स्मार्ट विशेषताएं',
    hiwSmartTitle: 'अंतर्निहित बुद्धिमत्ता',
    hiwOfflineSupport: 'ऑफलाइन सपोर्ट',
    hiwOfflineSupportDesc: 'रिपोर्ट आपके फोन पर सहेजी जाती हैं और कनेक्टिविटी वापस आने पर स्वचालित रूप से सिंक होती हैं।',
    hiwLocationIntel: 'स्थान बुद्धिमत्ता',
    hiwLocationIntelDesc: 'रिपोर्ट वास्तविक पृथ्वी ज्यामिति का उपयोग करके भौगोलिक रूप से अनुक्रमित हैं। आप वही देखते हैं जो आपके क्षेत्र के लिए प्रासंगिक है।',
    hiwWeatherDetection: 'मौसम पहचान',
    hiwWeatherDetectionDesc: 'CIVIX रीयल-टाइम वर्षा की निगरानी करता है। जब वर्षा का पता चलता है, तो आपको स्थिति रिपोर्ट करने के लिए सूचना मिलती है।',
    hiwSpamProtection: 'स्पैम सुरक्षा',
    hiwSpamProtectionDesc: 'रिपोर्ट पर दैनिक सीमा दुरुपयोग रोकती है जबकि सक्रिय नागरिकों को योगदान करने देती है।',
    hiwLiveAggregation: 'लाइव एकत्रीकरण',
    hiwLiveAggregationDesc: 'मैप क्षेत्र के अनुसार रिपोर्ट एकत्र करता है, गंभीरता स्तर और घनत्व दिखाता है। हमेशा ताज़ा, हमेशा तेज़।',
    hiwCtaTitle: 'इसे आज़माने के लिए तैयार?',
    hiwCtaDesc: 'ऐप डाउनलोड करें और रिपोर्टिंग शुरू करें। या लाइव मैप देखें कि अभी आपके शहर में क्या हो रहा है।',

    // Feedback Page
    fbEyebrow: 'प्रतिक्रिया',
    fbHeroTitle1: 'CIVIX को बनाने में मदद करें',
    fbHeroTitle2: 'बेहतर',
    fbHeroLead: 'हम यह आपके लिए बना रहे हैं। हमें बताएं क्या काम कर रहा है, क्या टूटा है, या आप क्या चाहते हैं। हर सुझाव सार्वजनिक है — पारदर्शिता विश्वास बनाती है।',
    fbFormTitle: 'अपने विचार साझा करें',
    fbSuccess: 'आपकी प्रतिक्रिया के लिए धन्यवाद — यह अब नीचे दिखाई दे रही है।',
    fbError: 'सबमिट करने में विफल। कृपया पुनः प्रयास करें।',
    fbNameLabel: 'नाम', fbNamePlaceholder: 'आपका नाम',
    fbEmailLabel: 'ईमेल (वैकल्पिक)', fbEmailPlaceholder: 'you@example.com',
    fbTypeLabel: 'किस प्रकार की प्रतिक्रिया?',
    fbTypeSuggestion: 'सुझाव', fbTypeBug: 'बग', fbTypeFeature: 'फीचर', fbTypeOther: 'अन्य',
    fbMessageLabel: 'आपकी प्रतिक्रिया', fbMessagePlaceholder: 'हमें बताएं आपके मन में क्या है...',
    fbSubmitting: 'सबमिट हो रहा है...', fbPostFeedback: 'प्रतिक्रिया पोस्ट करें',
    fbCommunityTitle: 'समुदाय प्रतिक्रिया',
    fbPost: 'पोस्ट', fbPosts: 'पोस्ट',
    fbFilterAll: 'सभी',
    fbEmpty: 'अभी तक कोई प्रतिक्रिया नहीं। अपने विचार साझा करने वाले पहले व्यक्ति बनें।',
    fbJustNow: 'अभी',
  },
  gu: {
    // Navbar
    home: 'હોમ', liveMap: 'લાઇવ મેપ', about: 'અમારા વિશે', howItWorks: 'કેવી રીતે કામ કરે છે', contact: 'સંપર્ક', getApp: 'એપ ડાઉનલોડ કરો',
    language: 'ભાષા',

    // Landing — Hero
    heroBadge: 'ભારતીય શહેરો માટે રીયલ-ટાઇમ પૂર ઇન્ટેલિજન્સ',
    heroTitle1: 'પૂરમાં ફસાશો નહીં', heroTitle2: 'તેનાથી આગળ રહો.',
    heroSub: 'CIVIX એક ક્રાઉડસોર્સ્ડ પ્લેટફોર્મ છે જે રીયલ-ટાઇમ જળભરાવ ચેતવણીઓ આપે છે, નાગરિકો અને શહેર સત્તાવાળાઓને ચોમાસામાં સુરક્ષિત નેવિગેટ કરવામાં મદદ કરે છે.',
    downloadAndroid: 'Android માટે ડાઉનલોડ કરો', seeHow: 'જુઓ કેવી રીતે કામ કરે છે →',
    mapLoading: 'લાઇવ મેપ — લોડ થઈ રહ્યો છે',
    legendSevere: 'ગંભીર', legendModerate: 'મધ્યમ', legendClear: 'સામાન્ય',
    liveFromCity: 'તમારા શહેરમાંથી લાઇવ',

    // Landing — Features
    featuresTitle: 'વિશેષતાઓ', feat1: 'લાઇવ મેપ', feat1d: 'ઇન્ટરેક્ટિવ મેપ પર રીયલ-ટાઇમ જળભરાવ અહેવાલો',
    feat2: 'સુરક્ષિત નેવિગેશન', feat2d: 'સ્માર્ટ રૂટિંગથી પૂરવાળા રસ્તાઓ ટાળો', feat3: 'હવામાન ચેતવણીઓ', feat3d: 'જ્યારે તમારા વિસ્તારમાં વરસાદ શરૂ થાય ત્યારે સૂચના મેળવો',
    feat4: 'સમુદાય ચકાસાયેલ', feat4d: 'ચોકસાઈ માટે અહેવાલોને અપવોટ/ડાઉનવોટ કરો', feat5: 'બહુભાષી', feat5d: 'અંગ્રેજી, હિન્દી અને ગુજરાતીમાં ઉપલબ્ધ',
    feat6: 'પાર્ટનર API', feat6d: 'ડિલિવરી અને લોજિસ્ટિક્સ કંપનીઓ માટે B2B API',
    whatCivixDoes: 'CIVIX શું કરે છે',
    builtForChaos: 'ભારતીય ચોમાસાની',
    indianMonsoons: 'અરાજકતા માટે બનાવેલ',
    featSectionSub: 'આ બીજી કોઈ હવામાન એપ નથી. CIVIX એ જમીની સ્તરનું ઇન્ટેલિજન્સ નેટવર્ક છે જે ખરેખર તે રસ્તાઓ પર ચાલતા લોકો દ્વારા સંચાલિત છે.',
    alertsThatMatter: 'મહત્વની ચેતવણીઓ',
    knowBeforeStepOut: 'બહાર નીકળતા પહેલા જાણો',
    knowBeforeDesc: 'જ્યારે કોઈ તમારી નજીક જળભરાવની જાણ કરે છે, ત્યારે તમને થોડી સેકન્ડોમાં પુશ નોટિફિકેશન મળે છે. આ આગાહી નથી — અત્યારે પાણીમાં ઊભેલી વ્યક્તિનો વાસ્તવિક અહેવાલ છે.',
    avgReportToAlert: 'અહેવાલથી ચેતવણી સુધીનો સરેરાશ સમય',
    liveHeatmap: 'લાઇવ હીટમેપ',
    seeCityLikeLocals: 'શહેરને સ્થાનિકોની જેમ જુઓ',
    seeCityDesc: 'રીયલ-ટાઇમમાં અપડેટ થતા રંગ-કોડેડ ગંભીરતા ઝોન. લાલ એટલે ટાળો, પીળો સાવધાની, લીલો સામાન્ય. ઓટો ડ્રાઇવર ના પાડે તે પહેલાં તમારો રસ્તો નક્કી કરો.',
    crowdsourced: 'ક્રાઉડસોર્સ્ડ',
    crowdsourcedOneTap: 'ક્રાઉડસોર્સ્ડ. એક ટેપમાં રિપોર્ટ કરો.',
    crowdsourcedDesc: 'કોઈ સરકારી સેન્સરની જરૂર નથી. નાગરિકો GPS-ચકાસાયેલ સ્થાન અને ગંભીરતા સાથે જળભરાવની જાણ કરે છે. જેટલા વધુ લોકો જાણ કરે, સિસ્ટમ એટલી સ્માર્ટ બને.',
    autoExpiryKeepsFresh: 'ઓટો-એક્સપાયરી ડેટાને તાજો રાખે છે',
    gpsLocationCaptured: 'GPS સ્થાન કેપ્ચર થયું',
    severityTagged: 'ગંભીરતા ટેગ થઈ',
    highKneeDeep: 'ઉચ્ચ — ઘૂંટણ સુધી પાણી',
    liveOnMap: 'મેપ પર લાઇવ',
    nearbyUsersAlerted: 'નજીકના વપરાશકર્તાઓને તરત જ ચેતવણી આપવામાં આવી',
    offlineMode: 'ઓફલાઇન મોડ', offlineModeDesc: 'ઓનલાઇન થાય ત્યારે રિપોર્ટ સિંક થાય છે',
    gpsVerified: 'GPS ચકાસાયેલ', gpsVerifiedDesc: 'સ્થાન-ચોક્કસ, છેડછાડ-પ્રૂફ અહેવાલો',
    autoExpiry: 'ઓટો-એક્સપાયરી', autoExpiryDesc: 'જૂના અહેવાલો 4 કલાક પછી દૂર થાય છે',
    worksAnywhere: 'ગમે ત્યાં કામ કરે', worksAnywhereDesc: 'GPS-આધારિત — કોઈ શહેર પ્રતિબંધ નથી',

    // Landing — How it Works
    howItWorksBadge: 'કેવી રીતે કામ કરે છે',
    threeStepsTo: 'ત્રણ પગલાં',
    saferCommutes: 'સુરક્ષિત મુસાફરી માટે',
    step1Title: 'ડાઉનલોડ કરો અને સાઇન અપ કરો',
    step1Desc: 'CIVIX એપ ડાઉનલોડ કરો. ઇમેઇલ OTP થી ચકાસો — લગભગ 30 સેકન્ડ લાગે છે. કોઈ ફોન નંબર નહીં, કોઈ સોશિયલ લોગિન નહીં.',
    step2Title: 'જે દેખાય તે રિપોર્ટ કરો',
    step2Desc: 'પાણીમાં ઊભા છો? એક ટેપ. તમારું GPS સ્થાન અને ગંભીરતા રેટિંગ તરત જ લાઇવ થાય છે. સમુદાય તેને રીયલ-ટાઇમમાં જુએ છે.',
    step3Title: 'પૂરથી આગળ રહો',
    step3Desc: 'ઘરેથી નીકળતા પહેલા ચેતવણી મેળવો. લાઇવ હીટમેપ તપાસો. સૂકો રસ્તો પસંદ કરો. તમારા શહેરને ઝડપથી પ્રતિસાદ આપવામાં મદદ કરો.',

    // Landing — Contrast
    withoutCivix: 'CIVIX વિના',
    withoutCivixDesc: 'તમે બહાર નીકળો છો, પૂર આવ્યું છે. કોઈએ ચેતવણી આપી નથી. તમે ફસાઈ ગયા. મ્યુનિસિપલ કોર્પોરેશનને ત્રણ દિવસ પછી અખબારના ફોટોથી ખબર પડે છે.',
    withCivix: 'CIVIX સાથે',
    withCivixDesc: 'બે ગલી દૂર કોઈ જળભરાવની જાણ કરે છે. તમને નીકળતા પહેલા ચેતવણી મળે છે. તમે હીટમેપ તપાસો છો, બીજો રસ્તો લો છો, અને સમયસર પહોંચો છો. શહેરને રીયલ-ટાઇમમાં ડેટા દેખાય છે.',

    // Landing — CTA
    ctaTitle: 'ચોમાસાની ઋતુ રાહ જોતી નથી.', ctaSub: 'તમારે પણ ન જોવી જોઈએ.',

    // Landing — FAQ
    faqBadge: 'વારંવાર પૂછાતા પ્રશ્નો',
    faqTitle: 'સામાન્ય',
    faqTitleGradient: 'પ્રશ્નો',
    faq1q: 'શું CIVIX મફત છે?', faq1a: 'હા. કોઈ જાહેરાતો નહીં, કોઈ પ્રીમિયમ ટિયર નહીં, કોઈ શરત નહીં. આ લોકોની મદદ માટે બનાવેલ નાગરિક ટેક પ્રોજેક્ટ છે.',
    faq2q: 'અહેવાલો કેટલા ચોક્કસ છે?', faq2a: 'દરેક અહેવાલ GPS-ચકાસાયેલ છે. જૂનો ડેટા 4 કલાક પછી આપોઆપ સમાપ્ત થાય છે જેથી તમે ફક્ત તે જ જુઓ જે અત્યારે થઈ રહ્યું છે.',
    faq3q: 'શું તે ઓફલાઇન કામ કરે છે?', faq3a: 'હા. અહેવાલો સ્થાનિક રીતે સાચવવામાં આવે છે અને ઓનલાઇન થાય ત્યારે આપોઆપ સિંક થાય છે.',
    faq4q: 'તે કયા શહેરોમાં ઉપલબ્ધ છે?', faq4a: 'GPS હોય ત્યાં ગમે ત્યાં. અમે અમદાવાદથી શરૂ કર્યું અને 50+ ભારતીય શહેરોમાં સક્રિય વપરાશકર્તાઓ છે.',
    faq5q: 'શું મારો ડેટા ખાનગી છે?', faq5a: 'અમે ફક્ત અહેવાલ સબમિટ કરતી વખતે સ્થાન એકત્ર કરીએ છીએ. કોઈ ટ્રેકિંગ નહીં, કોઈ ડેટા વેચાણ નહીં. ઇમેઇલ ફક્ત લોગિન માટે વપરાય છે.',

    // Footer
    footerDesc: 'સમુદાય-સંચાલિત જળભરાવ ચેતવણી પ્લેટફોર્મ જે ચોમાસાની ઋતુમાં ભારતીય શહેરોને સુરક્ષિત બનાવે છે.',
    footerDownloadApp: 'એપ ડાઉનલોડ કરો',
    footerPlatform: 'પ્લેટફોર્મ',
    footerLiveMap: 'લાઇવ મેપ', footerAboutUs: 'અમારા વિશે', footerContact: 'સંપર્ક', footerFeedback: 'પ્રતિસાદ', footerPrivacy: 'ગોપનીયતા નીતિ',
    footerResources: 'સંસાધનો', footerFeatures: 'વિશેષતાઓ', footerHowItWorks: 'કેવી રીતે કામ કરે છે', footerFAQ: 'વારંવાર પૂછાતા પ્રશ્નો',
    footerGetInTouch: 'સંપર્ક કરો', footerEmailUs: 'ઇમેઇલ કરો', footerSendMessage: 'સંદેશ મોકલો',
    footerBuiltIn: '© 2026 CIVIX — અમદાવાદ, ભારતમાં બનાવેલ',
    footerTagline: 'સ્માર્ટ શહેરો માટે ક્રાઉડસોર્સ્ડ પૂર ઇન્ટેલિજન્સ',
    footerRights: 'સર્વાધિકાર સુરક્ષિત.',

    // About Page
    aboutEyebrow: 'CIVIX વિશે',
    aboutHeroTitle1: 'અમે થાકી ગયા હતા ડૂબતા-ડૂબતા',
    aboutHeroTitle2: '',
    aboutHeroTitle3: 'અટકાવી શકાય તેવા પૂરમાં',
    aboutHeroLead: 'CIVIX એક સાદી નિરાશામાંથી શરૂ થયું: કોઈને કેમ ખબર નથી કે રસ્તો ડૂબેલો છે જ્યાં સુધી તેઓ તેમાં ઊભા ન હોય? અમે તે સાધન બનાવ્યું જે અમે દરેક ચોમાસામાં ઇચ્છતા હતા.',
    aboutStoryTitle: 'ભારતીય ચોમાસાની વાસ્તવિકતા',
    aboutStoryP1: 'દર વર્ષે એ જ ચક્ર પુનરાવર્તિત થાય છે. ભારે વરસાદ પડે છે. રસ્તાઓ મિનિટોમાં ડૂબી જાય છે. મુસાફરો કમર સુધીના પાણીમાં ચાલે છે. ઓટો ડ્રાઇવરો રસ્તા પર જવાની ના પાડે છે. ઓફિસો બંધ થાય છે. અને મ્યુનિસિપલ કોર્પોરેશનને ટ્વિટર પરથી ખબર પડે છે — કલાકો પછી.',
    aboutStoryP2: 'ઇન્ફ્રાસ્ટ્રક્ચરની ખામી વાસ્તવિક છે, પણ માહિતીની ખામી વધુ ખરાબ છે. કોઈ એવી સિસ્ટમ નથી જે તમને કહે "અત્યારે MG રોડ ન લો, ઘૂંટણ સુધી પાણી છે." એ જ અમે ઠીક કરવાનું નક્કી કર્યું.',
    aboutPullQuote: 'સમસ્યા ફક્ત પૂર નથી — એ છે કે કોઈને તેના વિશે ત્યાં સુધી ખબર નથી પડતી જ્યાં સુધી તેઓ પહેલેથી ફસાઈ ન ગયા હોય.',
    aboutWhatTitle: 'અમે શું બનાવ્યું',
    aboutWhatP1: 'CIVIX એક ક્રાઉડસોર્સ્ડ પૂર ઇન્ટેલિજન્સ પ્લેટફોર્મ છે. નાગરિકો તેમના ફોનથી GPS-ચકાસાયેલ સ્થાન અને ગંભીરતા સાથે જળભરાવની જાણ કરે છે. તે અહેવાલો તરત જ સાર્વજનિક હીટમેપ પર લાઇવ થાય છે. નજીકના વપરાશકર્તાઓને પુશ ચેતવણીઓ મળે છે. શહેર સત્તાવાળાઓને એનાલિટિક્સ અને હોટસ્પોટ ડેટા સાથે રીયલ-ટાઇમ ડેશબોર્ડ મળે છે.',
    aboutWhatP2: 'કોઈ મોંઘા IoT સેન્સર નહીં. કોઈ સરકારી કોન્ટ્રાક્ટ નહીં. ફક્ત એક મોબાઇલ એપ, એક મેપ, અને તે લોકો જે દરરોજ તે રસ્તાઓ પર ચાલે છે.',
    aboutStat1Val: '~30s', aboutStat1Desc: 'અહેવાલથી ચેતવણી સુધી',
    aboutStat2Val: 'GPS', aboutStat2Desc: 'દરેક અહેવાલ ચકાસાયેલ',
    aboutStat3Val: '4hr', aboutStat3Desc: 'ઓટો-એક્સપાયરી ડેટાને તાજો રાખે છે',
    aboutStat4Val: '24/7', aboutStat4Desc: 'હંમેશા ચાલુ, હંમેશા મફત',
    aboutWhoTitle: 'આ કોના માટે છે',
    aboutWhoCitizens: 'નાગરિકો',
    aboutWhoCitizensDesc: 'એપ ડાઉનલોડ કરો, ઇમેઇલ OTP થી ચકાસો, અને તમે અંદર છો. એક ટેપમાં જળભરાવની જાણ કરો. જ્યારે તમારી નજીક પૂરની જાણ થાય ત્યારે ચેતવણી મેળવો. બહાર નીકળતા પહેલા લાઇવ મેપ તપાસો — ખાસ કરીને ભારે વરસાદમાં.',
    aboutWhoCityAuth: 'શહેર સત્તાવાળાઓ',
    aboutWhoCityAuthDesc: 'એડમિન ડેશબોર્ડ તમને રીયલ-ટાઇમ ગંભીરતા ડેટા, ઐતિહાસિક વલણો અને ભૌગોલિક હોટસ્પોટ આપે છે. ડ્રેનેજ કામને પ્રાથમિકતા આપવા અને કટોકટી પ્રતિસાદ તૈનાત કરવા ક્રાઉડસોર્સ્ડ ઇન્ટેલિજન્સનો ઉપયોગ કરો.',
    aboutWhoResearchers: 'સંશોધકો',
    aboutWhoResearchersDesc: 'ભારતીય શહેરોમાં એકત્રિત, અનામી પૂર ડેટા. શહેરી ડ્રેનેજ પેટર્નનો અભ્યાસ કરો, ઇન્ફ્રાસ્ટ્રક્ચર નિષ્ફળતાઓ ઓળખો, અને ચોમાસાની તૈયારી માટે વધુ સારા આગાહી મોડેલ બનાવો.',
    aboutTechTitle: 'અંદરની ટેકનોલોજી',
    aboutTechDesc: 'CIVIX ઝડપ અને વિશ્વસનીયતા માટે બનાવેલ આધુનિક, પ્રોડક્શન-ગ્રેડ સ્ટેક પર ચાલે છે.',
    aboutCtaTitle1: 'ચોમાસાની ઋતુ રાહ જોતી નથી.',
    aboutCtaTitle2: 'તમારે પણ ન જોવી જોઈએ.',
    aboutCtaDesc: 'CIVIX ડાઉનલોડ કરો અને તમારા શહેર માટે રીયલ-ટાઇમ પૂર ઇન્ટેલિજન્સ બનાવવામાં મદદ કરો.',
    viewLiveMap: 'લાઇવ મેપ જુઓ',

    // Contact Page
    contactEyebrow: 'સંપર્ક',
    contactHeroTitle1: 'ચાલો',
    contactHeroTitle2: 'વાત કરીએ',
    contactHeroLead: 'કોઈ પ્રશ્ન, પ્રતિસાદ, અથવા શહેરોને પૂર-સ્માર્ટ બનાવવામાં સહયોગ કરવા માંગો છો? અમે સાંભળી રહ્યા છીએ.',
    contactEmailLabel: 'ઇમેઇલ',
    contactEmailHint: 'અમે સામાન્ય રીતે 24 કલાકમાં જવાબ આપીએ છીએ',
    contactLocationLabel: 'સ્થાન',
    contactLocationValue: 'અમદાવાદ, ગુજરાત, ભારત',
    contactSocialLabel: 'સોશિયલ',
    contactSocialHint: 'અપડેટ્સ માટે ફોલો કરો',
    contactFormTitle: 'અમને સંદેશ મોકલો',
    contactFormDesc: 'આ ભરો અને અમે તમારો સંપર્ક કરીશું. અથવા સીધો ઇમેઇલ કરો — જે અનુકૂળ હોય.',
    contactNameLabel: 'નામ', contactNamePlaceholder: 'તમારું નામ',
    contactEmailFieldLabel: 'ઇમેઇલ', contactEmailPlaceholder: 'you@example.com',
    contactSubjectLabel: 'વિષય', contactSubjectPlaceholder: 'આ શેના વિશે છે?',
    contactMessageLabel: 'સંદેશ', contactMessagePlaceholder: 'અમને જણાવો તમારા મનમાં શું છે...',
    contactSent: 'મોકલ્યો — મેઇલ ક્લાયન્ટ ખુલી રહ્યો છે...', contactSend: 'સંદેશ મોકલો',
    contactCollabNote: 'અમારી સાથે ભાગીદારી કરવા માંગો છો? અમે હંમેશા નાગરિક-લક્ષી ટીમો, મ્યુનિસિપલ સંસ્થાઓ અને શહેરી સ્થિતિસ્થાપકતા માટે કામ કરતી સંસ્થાઓ સાથે કામ કરવા તૈયાર છીએ. બસ અમને લખો.',

    // How It Works Page
    hiwEyebrow: 'CIVIX કેવી રીતે કામ કરે છે',
    hiwHeroTitle1: 'રીયલ-ટાઇમ પૂર ઇન્ટેલિજન્સ,',
    hiwHeroTitle2: 'નાગરિકો દ્વારા સંચાલિત',
    hiwHeroLead: 'CIVIX એક નાગરિક-સંચાલિત પ્લેટફોર્મ છે: રિપોર્ટિંગ માટે મોબાઇલ એપ, જાગૃતિ માટે લાઇવ સાર્વજનિક મેપ, અને તમને સુરક્ષિત રાખવા સ્માર્ટ ચેતવણીઓ. અહીં બતાવ્યું છે કે આ બધું કેવી રીતે જોડાય છે.',
    hiwScrollToExplore: 'એક્સપ્લોર કરવા સ્ક્રોલ કરો',
    hiwPlatformLabel: '01 — પ્લેટફોર્મ',
    hiwPlatformTitle: 'ત્રણ ભાગ, એક નેટવર્ક',
    hiwPlatformDesc: 'CIVIX ના ત્રણ ઘટકો છે જે મળીને રીયલ-ટાઇમ જળભરાવ ઇન્ટેલિજન્સ નેટવર્ક બનાવે છે.',
    hiwMobileApp: 'મોબાઇલ એપ',
    hiwMobileAppDesc: 'નાગરિકો GPS-ચકાસાયેલ સ્થાન અને ગંભીરતા સ્તર સાથે જળભરાવની જાણ કરે છે. અહેવાલો તરત જ સિંક થાય છે — અથવા ઓફલાઇન કતારમાં રહે છે અને પાછા ઓનલાઇન થાય ત્યારે સિંક થાય છે.',
    hiwLiveMap: 'લાઇવ મેપ',
    hiwLiveMapDesc: 'બધા સક્રિય જળભરાવ અહેવાલો બતાવતો સાર્વજનિક હીટમેપ. ગંભીરતા પ્રમાણે રંગ-કોડેડ — ઉચ્ચ માટે લાલ, મધ્યમ માટે નારંગી, નીચા માટે લીલો. લોગિન જરૂરી નથી.',
    hiwPushAlerts: 'પુશ ચેતવણીઓ',
    hiwPushAlertsDesc: 'જ્યારે કોઈ તમારી નજીક જળભરાવની જાણ કરે છે, ત્યારે તમને તરત જ સૂચિત કરવામાં આવે છે. સિસ્ટમ વરસાદ પણ શોધે છે અને સક્રિય રીતે નજીકના વપરાશકર્તાઓને સ્થિતિ જાણ કરવા કહે છે.',
    hiwReportingLabel: '02 — રિપોર્ટિંગ ફ્લો',
    hiwReportingTitle: 'જોવાથી ચેતવણી આપવા સુધી 30 સેકન્ડમાં',
    hiwReportingDesc: 'જળભરાવ જોવાથી લઈને નજીકના વપરાશકર્તાઓને ચેતવણી આપવા સુધીનો સમગ્ર ફ્લો લગભગ તાત્કાલિક છે.',
    hiwStep1Title: 'એપ ખોલો',
    hiwStep1Desc: 'જળભરાવવાળા વિસ્તારમાં ઊભા છો? CIVIX ખોલો અને "રિપોર્ટ" પર ટેપ કરો. એપ આપોઆપ તમારા GPS કોઓર્ડિનેટ્સ કેપ્ચર કરે છે.',
    hiwStep2Title: 'ગંભીરતા ટેગ કરો',
    hiwStep2Desc: 'પાણીની ઊંડાઈના આધારે નીચું, મધ્યમ અથવા ઉચ્ચ પસંદ કરો. અહેવાલ તમારા સ્થાન, ગંભીરતા અને સમય સાથે ટેગ થાય છે.',
    hiwStep3Title: 'અહેવાલ લાઇવ થાય છે',
    hiwStep3Desc: 'અહેવાલ તરત જ સાર્વજનિક હીટમેપ પર દેખાય છે. સ્થાનની આસપાસ 500 મીટરનો ઝોન દોરવામાં આવે છે. નજીકના વપરાશકર્તાઓને પુશ નોટિફિકેશન મળે છે.',
    hiwStep4Title: 'ઓટો-એક્સપાયરી તેને તાજું રાખે છે',
    hiwStep4Desc: 'અહેવાલો 4 કલાક પછી સમાપ્ત થાય છે. "સામાન્ય" અહેવાલો 500 મીટરની અંદર નજીકના જળભરાવ અહેવાલો રદ કરે છે. મેપ હંમેશા બતાવે છે કે અત્યારે શું થઈ રહ્યું છે.',
    hiwAuthLabel: '03 — શરૂ કરવું',
    hiwAuthTitle: 'સરળ, પાસવર્ડ-રહિત સાઇન-અપ',
    hiwAuthDesc: 'કોઈ ફોન નંબર નહીં, કોઈ સોશિયલ લોગિન નહીં, કોઈ પાસવર્ડ યાદ રાખવાની જરૂર નથી.',
    hiwAuthEnterEmail: 'ઇમેઇલ દાખલ કરો',
    hiwAuthVerifyOTP: 'OTP ચકાસો',
    hiwAuthYoureIn: 'તમે અંદર છો',
    hiwPrivacyTitle: 'ગોપનીયતા પ્રથમ',
    hiwPrivacyDesc: 'અમે ફક્ત પ્રમાણીકરણ માટે તમારો ઇમેઇલ એકત્ર કરીએ છીએ. કોઈ ફોન નંબર નહીં, કોઈ સોશિયલ પ્રોફાઇલ નહીં, કોઈ ટ્રેકિંગ નહીં. તમારા અહેવાલો મેપ પર અનામી રીતે દેખાય છે — તમારી ઓળખ ક્યારેય જાહેરમાં બતાવવામાં આવતી નથી.',
    hiwSmartLabel: '04 — સ્માર્ટ વિશેષતાઓ',
    hiwSmartTitle: 'અંતર્નિર્મિત બુદ્ધિમત્તા',
    hiwOfflineSupport: 'ઓફલાઇન સપોર્ટ',
    hiwOfflineSupportDesc: 'અહેવાલો તમારા ફોન પર સાચવવામાં આવે છે અને કનેક્ટિવિટી પાછી આવે ત્યારે આપોઆપ સિંક થાય છે.',
    hiwLocationIntel: 'સ્થાન બુદ્ધિમત્તા',
    hiwLocationIntelDesc: 'અહેવાલો વાસ્તવિક પૃથ્વી ભૂમિતિનો ઉપયોગ કરીને ભૌગોલિક રીતે અનુક્રમિત છે. તમે તે જ જુઓ છો જે તમારા વિસ્તાર માટે સંબંધિત છે.',
    hiwWeatherDetection: 'હવામાન શોધ',
    hiwWeatherDetectionDesc: 'CIVIX રીયલ-ટાઇમ વરસાદનું નિરીક્ષણ કરે છે. જ્યારે વરસાદ શોધાય છે, ત્યારે તમને સ્થિતિ જાણ કરવા સૂચના મળે છે.',
    hiwSpamProtection: 'સ્પામ સુરક્ષા',
    hiwSpamProtectionDesc: 'અહેવાલો પર દૈનિક મર્યાદા દુરુપયોગ અટકાવે છે જ્યારે સક્રિય નાગરિકોને યોગદાન આપવા દે છે.',
    hiwLiveAggregation: 'લાઇવ એકત્રીકરણ',
    hiwLiveAggregationDesc: 'મેપ વિસ્તાર પ્રમાણે અહેવાલો એકત્ર કરે છે, ગંભીરતા સ્તરો અને ઘનતા બતાવે છે. હંમેશા તાજું, હંમેશા ઝડપી.',
    hiwCtaTitle: 'અજમાવવા તૈયાર છો?',
    hiwCtaDesc: 'એપ ડાઉનલોડ કરો અને રિપોર્ટિંગ શરૂ કરો. અથવા લાઇવ મેપ તપાસો કે અત્યારે તમારા શહેરમાં શું થઈ રહ્યું છે.',

    // Feedback Page
    fbEyebrow: 'પ્રતિસાદ',
    fbHeroTitle1: 'CIVIX ને બનાવવામાં મદદ કરો',
    fbHeroTitle2: 'વધુ સારું',
    fbHeroLead: 'અમે આ તમારા માટે બનાવી રહ્યા છીએ. અમને જણાવો શું કામ કરી રહ્યું છે, શું તૂટેલું છે, અથવા તમે શું ઇચ્છો છો. દરેક સૂચન સાર્વજનિક છે — પારદર્શિતા વિશ્વાસ બનાવે છે.',
    fbFormTitle: 'તમારા વિચારો શેર કરો',
    fbSuccess: 'તમારા પ્રતિસાદ બદલ આભાર — તે હવે નીચે દેખાય છે.',
    fbError: 'સબમિટ કરવામાં નિષ્ફળ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    fbNameLabel: 'નામ', fbNamePlaceholder: 'તમારું નામ',
    fbEmailLabel: 'ઇમેઇલ (વૈકલ્પિક)', fbEmailPlaceholder: 'you@example.com',
    fbTypeLabel: 'કયા પ્રકારનો પ્રતિસાદ?',
    fbTypeSuggestion: 'સૂચન', fbTypeBug: 'બગ', fbTypeFeature: 'ફીચર', fbTypeOther: 'અન્ય',
    fbMessageLabel: 'તમારો પ્રતિસાદ', fbMessagePlaceholder: 'અમને જણાવો તમારા મનમાં શું છે...',
    fbSubmitting: 'સબમિટ થઈ રહ્યું છે...', fbPostFeedback: 'પ્રતિસાદ પોસ્ટ કરો',
    fbCommunityTitle: 'સમુદાય પ્રતિસાદ',
    fbPost: 'પોસ્ટ', fbPosts: 'પોસ્ટ',
    fbFilterAll: 'બધા',
    fbEmpty: 'હજુ સુધી કોઈ પ્રતિસાદ નથી. તમારા વિચારો શેર કરનાર પ્રથમ બનો.',
    fbJustNow: 'હમણાં જ',
  },
};

const LANG_LABELS: Record<Lang, string> = { en: 'EN', hi: 'हि', gu: 'ગુ' };

interface LangCtx { lang: Lang; setLang: (l: Lang) => void; t: (k: string) => string; }
const Ctx = createContext<LangCtx>({ lang: 'en', setLang: () => {}, t: k => k });
export const useLang = () => useContext(Ctx);
export { LANG_LABELS };

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem('civix_lang');
    return (saved === 'hi' || saved === 'gu') ? saved : 'en';
  });

  const changeLang = (l: Lang) => { setLang(l); localStorage.setItem('civix_lang', l); };
  const t = (key: string) => translations[lang]?.[key] || translations.en[key] || key;

  return <Ctx.Provider value={{ lang, setLang: changeLang, t }}>{children}</Ctx.Provider>;
};
